### ISSUE TITLE
How do you add other podcasts?

### ISSUE THREAD

**Issue by alexellis** [kissgyorgy/simple-podcast-dl#23]
How do you add other podcasts? Is that part of the vision?

For instance I'd like to listen to https://kubernetespodcast.com

**Comment by kissgyorgy** [comment]
Currently, we have to modify the code: https://github.com/kissgyorgy/simple-podcast-dl/blob/master/podcast_dl/podcasts.py
because there are parsers for every Podcast's RSS, but I plan to separate it. For now, I will add it for you.

**Comment by kissgyorgy** [comment]
I made a new release, you can install it with `pip3` and let me know if you have any problem with it.
